/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventday1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import org.checkerframework.checker.units.qual.A;

public class App {

    public static void main(String[] args) throws Exception {
        ArrayList<String> input = new ArrayList<>();
        File file = new File("/home/redmark/Documents/Code/Advent/Day1/input.txt");
        BufferedReader bufferedReader = new BufferedReader(new FileReader(file));
        String inputStr;
        while((inputStr=bufferedReader.readLine())!=null)
        {
          input.add(inputStr);
        }



       Integer  sol = new Solution().solution(input);
    }
}

class Solution {

public Integer solution(ArrayList<String> inputparam)
{
  Integer answer = 0; 
  List<Integer>listofNums = new ArrayList<>(); 
  for (String input : inputparam)
  {
   listofNums= input.chars().filter(a->a>48 & a<58).map(a->a-48).collect(ArrayList::new, ArrayList::add, ArrayList::addAll);
   System.out.println(listofNums);
   if(listofNums.size()>0)
   {
     Integer number = (listofNums.get(0)*10)+listofNums.get(listofNums.size()-1);
     answer = answer+number;
     //System.out.println(number);
   }
   else
   {
   int number = 0;  
   answer = answer+number;
   System.out.println(answer);
   }
System.out.println(answer);

}

return 0; 


}
}
